setting common product id as well

diff --git a/.github/workflows/oss_pygoat-devsecops.yml b/.github/workflows/oss_pygoat-devsecops.yml
--- a/.github/workflows/oss_pygoat-devsecops.yml
+++ b/.github/workflows/oss_pygoat-devsecops.yml
@@ -19,6 +19,7 @@ env:
   listArtifacts: true
   DEFECTDOJO_URL: https://defectdojo-002.cad4devops.com:8443/api/v2
   DEFECTDOJO_COMMONUSER: Student000
+  DEFECTDOJO_COMMONPRODUCTNAME: GitHub-OSS-pygoat-devsecops-workshop-001-product-000
   appUrl: http://gh-pygoat-test.cad4devops.com
   containerName: owaspzapproxy
   doActiveScan: false
@@ -64,6 +65,18 @@ jobs:
           else
             echo "DEFECTDOJO_TOKEN: $DEFECTDOJO_TOKEN"
             echo "DEFECTDOJO_TOKEN is set"
+            # now get the product id
+            DEFECTDOJO_PRODUCTID=`curl --fail --location --request GET "${{ env.DEFECTDOJO_URL }}/products/?name=${{ env.DEFECTDOJO_COMMONPRODUCTNAME }}" \
+              --header "Authorization: Token $DEFEECTDOJO_TOKEN" | jq -r '.results[0].id'`
+            if [ -z "${DEFECTDOJO_PRODUCTID}" ]; then
+              echo "Error: Failed to get product id for pygoat. Please check the product name."
+              exit 1
+            else
+              echo "DEFECTDOJO_PRODUCTID: $DEFECTDOJO_PRODUCTID"
+              echo "DEFECTDOJO_PRODUCTID is set"
+              echo "DEFECTDOJO_PRODUCTID: $DEFECTDOJO_PRODUCTID" >> $GITHUB_ENV
+              exit 0
+            fi
             exit 0
           fi
       - name: checkout
