getting feedback to set secrets step by step

diff --git a/.github/workflows/oss_pygoat-devsecops.yml b/.github/workflows/oss_pygoat-devsecops.yml
--- a/.github/workflows/oss_pygoat-devsecops.yml
+++ b/.github/workflows/oss_pygoat-devsecops.yml
@@ -301,6 +301,17 @@ jobs:
         uses: actions/download-artifact@v4.1.0
         with:
           path: "${{ github.workspace }}"
+      - name: check if secrets are set
+        run: |-
+          echo "DEFECTDOJO_URL: ${{ env.DEFECTDOJO_URL }}"
+          echo "DEFECTDOJO_PRODUCTID: ${{ vars.DEFECTDOJO_PRODUCTID }}"
+          echo "DEFECTDOJO_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}"
+          # check if the token is set
+          if [ -z "${{ secrets.DEFECTDOJO_TOKEN }}" ]; then
+            echo "Error: DEFECTDOJO_TOKEN is not set. Please set the secret in the dev environment."
+            echo "Alternatively, you can use the common Student000 user."
+            exit 1
+          fi
       - name: Create DefectDojo Engagement
         run: |-
           TODAY=`date +%Y-%m-%d`
